### ISSUE TITLE
Incompatible with Easy Magic

### ISSUE THREAD

**Issue by p3lim** [RedstoneParadox/Better-Enchantment-Boosting#2]
[Easy Magic](https://www.curseforge.com/minecraft/mc-mods/easy-magic-fabric) has some nice features for retaining the inventory, rendering the inventory on the enchanting table, and ignoring collision-free things in the way. Would be nice if it was compatible.

(There are other features in that mod too that I personally find overpowered, and have disabled as far as it's possible)

If you are unable/unwilling to make it compatible with that mod, would you be willing to add inventory retaining on the enchanting table and ignoring collision-free things in the way as (optional) features instead? I'm not expecting the rendering bit if so.

**Comment by RedstoneParadox** [comment]
Define incompatible; does it crash? Or do some features simply not work?

**Comment by p3lim** [comment]
Books/candles beyond the vanilla limit simply don't work. I assume Easy Magic replaces the block somehow.

**Comment by RedstoneParadox** [comment]
Easy Magic replaces the vanilla screen with a custom one, hence my code for counting bookshelves beyond the vanilla limit is never called. I can look into adding some of its features to this mod, though. I will point out that BEB already ignores many blocks when searching for bookshelves that it would make sense to ignore.

**Comment by RedstoneParadox** [comment]
I've taken another look and realized that I can just mixin to their screen. Should be an easy fix.

**Comment by RedstoneParadox** [comment]
Fixed in 1.2.2
